### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by AkosLukacs** [Prolucid/fable-react-toolbox#11]
Hi!

First, thank you for the work you put into this!

Wanted to ask before sending more pull requests, since looks like you are working on it right now...

Trying to use the Autocomplete, but looks like some properties are missing such as `onQueryChange`, or for example there is `AutocompleteTheme.Label` in the fable definition, but not found that in the  documentation or the source.

Should I try to update the definition and send a pull?

A minor inconvenience: paket.exe is gitignored. Just downloading paket.bootstrapper.exe, and putting it in it's place solves the problem. Should I send a pull with the latest paket.bootstrapper.exe commited to the source?
Also adding `storage:none` to paket.dependencies would cut the size of packages folder 450Mb -> 160Mb.

**Comment by 2sComplement** [comment]
PRs are definitely welcome! All of the items you mentioned are valid and I would gladly accept them. 
I originally used Ts2Fable to generate these bindings and have not fully tested all the components, so I'm not surprised that there are inconsistencies.  Thanks for your help.
