### ISSUE TITLE
Fable 1.x bindings

### ISSUE THREAD

**Issue by et1975** [Prolucid/fable-react-toolbox#3]

**Comment by 2sComplement** [comment]
These are available on Nuget and on the fableup branch. Keeping this issue open to remind myself to eventually create a PR.

**Comment by DmitryBatalov** [comment]
Does anybody has taken that issue? I'd like to take that to work on that with mentee.

**Comment by 2sComplement** [comment]
Bindings available on Nuget should work with latest fable. Does that answer your question?

**Comment by DmitryBatalov** [comment]
Yes, thanks. Will find another one.
