### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Prolucid/fable-react-toolbox#5]
I added the nuget package to paket.dependencies and to paket.references, then performed `paket install`. It brings the nuget and npm packages, but nothing was added to the project file. I had to add the fs file manually, like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>

        <Compile Include="node_modules\fable-react-toolbox\Fable.Helpers.ReactToolbox.fs"/>

        <!-- Global to the app -->
        <Compile Include="Global.fs"/>
        ......
```

**Comment by 2sComplement** [comment]
I haven't tested with netstandard2.0.
Have a look at the [starter project](https://github.com/Prolucid/fable-react-toolbox-starter/tree/fableup), maybe that will help.
